version: '2'

services:
    openvpn:
        cap_add:
            - NET_ADMIN
        image: kylemanna/openvpn
        container_name: openvpn
        ports:
            - "1194:1194/udp"
            - 8080:80
        restart: always
        volumes:
            - ./openvpn-data/conf:/etc/openvpn
        extra_hosts:
            - tart.signal:10.0.0.33
            - tart.tartza:10.0.0.22
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"

    reverse:
        image: nginx
        #ports:
        #    - 8080:80
        network_mode: "service:openvpn"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/html:/var/www/html
            - ~/cache:/cache
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"
