obs:
	python acquire.py --data-dir /freenas2/tart/data/

lobs:
	python acquire.py --data-directory test

fobs:
	python acquire.py --debug --data-directory test

debug10:
	python spartan6_spi_acquire.py --speed 8 --bramexp 10 --fast --debug --reset

debug:
	python spartan6_spi_acquire.py --speed 8 --bramexp 21 --fast --debug --reset

