# Run the object position server container. 
version: '2'

services:
    object-position-server:
        build: 
            context: .
        ports:
            - 8876:8876
        restart: unless-stopped
        environment:
            - FLASK_DEBUG=0
        volumes:
            - ~/catalog_cache:/object_position_server/orbit_data
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "1m"

    api_doc_server:
        build:
            context: .
            dockerfile: Dockerfile.apidoc 
        ports: 
            - 8877:80
        restart: unless-stopped

