set_property PACKAGE_PIN K17 [get_ports rx_clk_16]
set_property PACKAGE_PIN T11 [get_ports {antenna[0]}]
set_property PACKAGE_PIN T10 [get_ports {antenna[1]}]
set_property PACKAGE_PIN U13 [get_ports {antenna[2]}]
set_property PACKAGE_PIN V13 [get_ports {antenna[3]}]
set_property PACKAGE_PIN T14 [get_ports {antenna[4]}]
set_property PACKAGE_PIN T15 [get_ports {antenna[5]}]
set_property IOSTANDARD LVTTL [get_ports rx_clk_16]
set_property IOSTANDARD LVTTL [get_ports {antenna[0]}]
set_property IOSTANDARD LVTTL [get_ports {antenna[1]}]
set_property IOSTANDARD LVTTL [get_ports {antenna[2]}]
set_property IOSTANDARD LVTTL [get_ports {antenna[3]}]
set_property IOSTANDARD LVTTL [get_ports {antenna[4]}]
set_property IOSTANDARD LVTTL [get_ports {antenna[5]}]


set_property IOSTANDARD LVTTL [get_ports clk6x]
set_property IOSTANDARD LVTTL [get_ports clk6n]
set_property IOSTANDARD LVTTL [get_ports clk12x]
set_property IOSTANDARD LVTTL [get_ports clk_locked]
set_property IOSTANDARD LVTTL [get_ports clk_o]
set_property PACKAGE_PIN M18 [get_ports clk_o]
set_property PACKAGE_PIN M17 [get_ports clk_locked]
set_property PACKAGE_PIN L20 [get_ports clk12x]
set_property PACKAGE_PIN L19 [get_ports clk6x]
set_property PACKAGE_PIN F17 [get_ports clk6n]
