apiVersion: batch/v1
kind: Job
metadata:
  name: tart-cal
spec:
  template:
    spec:
      containers:
        - env:
            - name: TART_API
              value: https://tart.elec.ac.nz/signal/
            - name: TART_CAL_INT
              value: "30"
            - name: TART_LOGIN_PW
              value: sharkbait
            - name: TART_NCAL
              value: "6"
          image: ghcr.io/tmolteno/tart_cal:main
          name: tart-cal
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: data-volume
      restartPolicy: OnFailure
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
status: {}
