apiVersion: batch/v1
kind: Job
metadata:
  name: tart-cal
spec:
  template:
    spec:
      containers:
        - env:
            - name: TART_API
              value: https://tart.elec.ac.nz/signal/
            - name: TARGET
              value: signal
            - name: TART_CAL_INT
              value: "20"
            - name: TART_NCAL
              value: "3"
            - name: TART_CAL_ARGS
              value: ""
            - name: TART_CAL_ITERATIONS
              value: "1000"
            - name: TART_LOGIN_PW
              value: sharkbait
            - name: TART_UPLOAD
              value: "1`"
          image: ghcr.io/tmolteno/tart_cal:latest
          name: tart-cal
          resources: {}
          volumeMounts:
            - mountPath: /work
              name: data-volume
      restartPolicy: OnFailure
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
status: {}
